name = input("enter your name: ")
last_name = input("enter your last name: ")
age = input("enter your age: ")
print(name + " " + last_name + " " + "is" + " " + age + " " + "years old")
# 2)
firstnum = input("enter the first number: ")
secondnum = input("enter the second number: ")
print(int(firstnum) + int(secondnum))
print(int(firstnum) - int(secondnum))
print(int(firstnum) / int(secondnum))
print(int(firstnum) * int(secondnum))
# 3)
user1 = input("enter your user: ")
print(user1)
# 4)
math = 20 + 20
math2 = math - 10
math3 = math2 * 2
print(math3)
# 5)
academy = input("enter your academy: ")
school = input("enter your school: ")
name = input("enter your name: ")
last_name = input("enter your last name: ")
age = input("enter your age: ")
print(academy)
print(school)
print(name)
print(last_name)
print(age)