name = input("enter your name: ")
surname = input("enter your surname: ")
print(name + " " + surname)
num1 = input("enter the first number: ")
num2 = input('enter the second number: ')
print(int(num1) + int(num2))
print(int(num1) - int(num2))
print(int(num1) / int(num2))
print(int(num1) * int(num2))
print(int(num1) // int(num2))
print(int(num1) ** int(num2))