birth = input("enter your birth year: ")
year = input("enter this year: ")
print(int(year) - int(birth))
quadrilateral1 = input("enter the first side of the quadrilateral: ")
quadrilateral2 = input("enter the second side of the quadrilateral: ")
print(int(quadrilateral1) * int(quadrilateral2))
print(2*(int(quadrilateral1) + int(quadrilateral2)))
distance = input("enter the distance from your home to school in kilometres: ")
print(int(1000) * int(distance))

print(int(100000) * int(distance))

print(int(1000000) * int(distance))
name = input("enter your name: ")
surname = input("enter your surname: ")
favorite_color = input("enter your favorite color: ")
parents_name = input("enter your parents name: ")
favorite_car = input("enter your favorite car: ")
hobby = input("enter your three hobby: ")
print(name + " " + surname + "'s" + " " + "favorite color is" + " " + favorite_color + " " + "his favorite car is" + " " + favorite_car + " " + "his parents name is" + " " + parents_name + " " + "his hobby is" + " " + hobby)
number = input("enter double digit number: ")
print(int(number) // 3)
print(int(number) % 3)
print(int(number) // 3 + int(number) % 3)